#!/bin/bash
set -euo pipefail

COREOS_KUBERNETES_ROOT=$(git rev-parse --show-toplevel)
KUBERNETES_MOUNT_DIR="/go/src/github.com/kubernetes-incubator/kube-aws"

docker run --rm -i \
    -v "${COREOS_KUBERNETES_ROOT}:${KUBERNETES_MOUNT_DIR}:z" -w ${KUBERNETES_MOUNT_DIR} \
    --entrypoint /bin/bash golang:1.7.3  <<EOF
#!/bin/bash
set -euo pipefail
wget -O /tmp/glide.tgz https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
tar -zxvf /tmp/glide.tgz -C /tmp
mv /tmp/linux-amd64/glide /usr/local/bin
./build-release-binaries
EOF
