// +build ignore

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strings"
	"text/template"
	"time"
)

type Entry struct {
	Filename string
	VarName  string
}

type Data struct {
	Vars []Var
	Now  time.Time
}

type Var struct {
	Name string
	Data string
}

var tmpl = template.Must(template.New("files.go").Parse(`package config

// This file was generated by files_gen.go. DO NOT EDIT by hand.
//
// Last generated at {{ .Now }}.

var (
{{ range $i, $var := .Vars }}	{{ $var.Name }} = _{{ $var.Name }}
{{ end }}
)

var (
{{ range $i, $var := .Vars }}	_{{ $var.Name }} = {{ $var.Data  }}{{ end }}
)
`))

func toGoByteSlice(sli []byte) string {
	buff := new(bytes.Buffer)
	fmt.Fprintf(buff, "[]byte{\n")
	for i, b := range sli {
		if i%10 == 0 {
			fmt.Fprintf(buff, "\t%#x,", b)
		} else {
			fmt.Fprintf(buff, " %#x,", b)
		}
		if (i+1)%10 == 0 {
			fmt.Fprintln(buff)
		}
	}
	fmt.Fprintf(buff, "\n}\n")
	return buff.String()
}

func main() {
	entries := []Entry{}
	args := os.Args[1:]
	for _, arg := range args {
		parts := strings.Split(arg, "=")
		varname, filename := parts[0], parts[1]
		entry := Entry{
			Filename: filename,
			VarName:  varname,
		}
		entries = append(entries, entry)
	}

	vars := make([]Var, len(entries))
	for i, file := range entries {
		data, err := ioutil.ReadFile(file.Filename)
		if err != nil {
			log.Fatal(err)
		}
		vars[i] = Var{file.VarName, toGoByteSlice(data)}
	}

	f, err := os.OpenFile("files.go", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	data := Data{vars, time.Now().UTC()}
	if err := tmpl.Execute(f, data); err != nil {
		log.Fatal("Failed to render template:", err)
	}
}
