#!/bin/bash
set -euo pipefail

default() {
  test -z "$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)"
  go test -v $(go list ./... | grep -v '/vendor/')
  go vet $(go list ./... | grep -v '/vendor/')
}

with-cover() {
  test -z "$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)"
  for d in $(go list ./... | grep -v '/vendor/'); do
    go test -v --race -coverprofile=profile.out -covermode=atomic $d
    if [ -f profile.out ]; then
      cat profile.out >> coverage.txt
      rm profile.out
    fi
  done
  go vet $(go list ./... | grep -v '/vendor/')
}

if [ -z ${1+x} ]; then
  default
else
  "$@"
fi
